BEGIN TRANSACTION;

UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 1;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 2;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 3;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 4;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 5;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 6;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 7;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 8;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 9;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 10;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 11;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 12;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 13;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 14;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 15;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 16;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 17;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 18;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 19;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 20;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 21;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 22;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 23;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 24;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 25;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 26;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 27;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 28;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 29;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 30;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 31;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 32;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 33;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 34;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 35;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 36;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 37;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 38;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 39;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 40;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 41;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 42;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 43;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 44;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 45;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 46;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 47;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 48;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 49;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 50;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 51;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 52;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 53;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 54;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 55;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 56;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 57;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 58;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 59;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 60;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 61;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 62;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 63;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 64;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 65;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 66;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 67;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 68;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 69;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 70;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 71;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 72;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 73;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 74;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 75;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 76;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 77;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 78;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 79;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 80;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 81;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 82;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 83;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 84;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 85;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 86;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 87;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 88;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 89;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 90;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 91;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 92;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 93;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 94;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 95;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 96;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 97;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 98;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 99;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 100;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 101;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 102;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 103;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 104;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 105;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 106;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 107;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 108;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 109;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 110;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 111;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 112;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 113;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 114;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 115;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 116;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 117;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 118;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 119;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 120;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 121;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 122;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 123;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 124;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 125;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 126;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 127;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 128;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 129;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 130;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 131;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 132;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 133;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 134;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 135;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 136;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 137;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 138;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 139;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 140;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 141;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 142;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 143;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 144;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 145;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 146;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 147;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 148;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 149;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 150;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 151;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 152;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 153;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 154;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 155;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 156;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 157;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 158;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 159;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 160;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 161;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 162;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 163;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 164;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 165;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 166;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 167;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 168;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 169;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 170;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 171;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 172;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 173;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 174;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 175;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 176;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 177;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 178;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 179;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 180;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 181;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 182;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 183;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 184;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 185;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 186;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 187;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 188;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 189;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 190;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 191;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 192;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 193;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 194;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 195;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 196;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 197;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 198;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 199;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 200;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 201;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 202;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 203;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 204;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 205;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 206;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 207;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 208;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 209;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 210;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 211;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 212;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 213;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 214;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 215;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 216;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 217;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 218;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 219;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 220;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 221;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 222;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 223;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 224;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 225;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 226;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 227;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 228;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 229;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 230;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 231;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 232;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 233;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 234;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 235;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 236;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 237;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 238;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 239;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 240;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 241;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 242;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 243;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 244;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 245;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 246;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 247;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 248;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 249;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 250;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 251;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 252;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 253;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 254;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 255;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 256;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 257;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 258;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 259;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 260;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 261;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 262;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 263;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 264;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 265;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 266;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 267;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 268;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 269;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 270;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 271;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 272;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 273;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 274;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 275;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 276;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 277;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 278;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 279;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 280;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 281;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 282;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 283;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 284;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 285;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 286;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 287;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 288;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 289;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 290;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 291;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 292;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 293;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 294;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 295;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 296;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 297;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 298;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 299;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 300;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 301;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 302;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 303;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 304;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 305;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 306;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 307;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 308;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 309;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 310;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 311;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 312;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 313;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 314;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 315;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 316;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 317;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 318;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 319;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 320;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 321;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 322;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 323;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 324;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 325;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 326;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 327;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 328;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 329;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 330;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 331;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 332;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 333;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 334;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 335;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 336;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 337;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 338;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 339;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 340;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 341;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 342;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 343;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 344;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 345;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 346;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 347;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 348;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 349;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 350;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 351;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 352;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 353;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 354;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 355;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 356;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 357;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 358;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 359;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 360;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 361;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 362;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 363;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 364;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 365;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 366;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 367;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 368;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 369;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 370;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 371;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 372;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 373;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 374;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 375;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 376;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 377;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 378;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 379;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 380;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 381;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 382;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 383;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 384;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 385;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 386;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 387;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 388;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 389;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 390;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 391;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 392;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 393;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 394;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 395;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 396;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 397;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 398;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 399;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 400;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 401;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 402;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 403;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 404;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 405;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 406;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 407;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 408;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 409;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 410;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 411;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 412;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 413;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 414;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 415;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 416;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 417;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 418;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 419;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 420;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 421;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 422;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 423;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 424;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 425;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 426;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 427;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 428;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 429;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 430;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 431;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 432;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 433;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 434;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 435;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 436;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 437;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 438;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 439;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 440;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 441;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 442;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 443;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 444;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 445;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 446;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 447;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 448;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 449;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 450;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 451;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 452;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 453;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 454;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 455;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 456;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 457;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 458;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 459;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 460;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 461;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 462;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 463;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 464;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 465;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 466;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 467;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 468;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 469;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 470;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 471;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 472;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 473;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 474;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 475;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 476;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 477;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 478;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 479;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 480;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 481;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 482;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 483;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 484;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 485;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 486;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 487;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 488;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 489;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 490;
UPDATE Airplane SET Company = 'Croatia Airlines' WHERE AirplaneId = 491;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 492;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 493;
UPDATE Airplane SET Company = 'Delta' WHERE AirplaneId = 494;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 495;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 496;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 497;
UPDATE Airplane SET Company = 'Ryanair' WHERE AirplaneId = 498;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 499;
UPDATE Airplane SET Company = 'AirDUMP' WHERE AirplaneId = 500;


COMMIT;